name: CI
on:
    - pull_request
    - workflow_dispatch

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 14.17.0

            # npm cache
            - name: Get npm cache directory
              id: npm-cache-dir
              run: echo "::set-output name=dir::$(npm config get cache)"
            - uses: actions/cache@v3
              id: npm-cache
              with:
                  path: ${{ steps.npm-cache-dir.outputs.dir }}
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Install dependencies
              run: npm ci
            - name: Format check
              run: npm run format:check:ci
            - name: Lint check
              run: npm run lint:check:ci
              if: always()
